# docker-compose.yml
version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/bilanzkreis
      - NATS_URL=nats://nats:4222
      - JWT_SECRET=dev-secret
      - JWT_EXPIRATION=24h
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - nats

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongodb_data: